[package]
name = "stock_server"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
rand = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
anyhow = { workspace = true }
crossbeam-channel = { workspace = true }
stock_lib = { path = "../stock_lib", features=["random_generation"] }
